#!/usr/bin/env python

from twisted.python import log
from twisted.internet import epollreactor
import sys

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print >>sys.stderr, "usage: run config"
        sys.exit(111)
    yaml = sys.argv[1]
    epollreactor.install()
    log.startLogging(sys.stdout)
    from sabo import start
    start(yaml)

# vim: ts=4 sw=4 ai et
